In [1]:
import numpy as np
import pandas as pd

This is where I explain what I'm doing...

# New section

$$y_{it}=\lambda_i F_t + y_{it}^o$$

In [2]:
A = np.array([1,2,3])

In [4]:
A.shape

(3,)

In [5]:
B = np.array([4,5,6])
A+B

array([5, 7, 9])

In [6]:
5*A

array([ 5, 10, 15])

In [7]:
A.sum()

6

In [8]:
A.mean()

2.0

In [9]:
np.sum(A)

6

In [10]:
np.cumsum(A)

array([1, 3, 6])

In [11]:
np.diff(A)

array([1, 1])

In [12]:
A.prod()

6

In [13]:
C = [[1,2],[3,4],[5,6]]
D = [[5],[8]]
C = np.matrix(C)
D = np.matrix(D)

In [17]:
np.dot(C,D)   # Specifically matrix multiplication

matrix([[21],
        [47],
        [73]])

In [20]:
np.multiply(C,C)

matrix([[ 1,  4],
        [ 9, 16],
        [25, 36]])

In [21]:
np.divide(C,C)

matrix([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [22]:
np.log(C)

matrix([[0.        , 0.69314718],
        [1.09861229, 1.38629436],
        [1.60943791, 1.79175947]])

In [23]:
C.T

matrix([[1, 3, 5],
        [2, 4, 6]])

In [24]:
np.dot(C.T,C)

matrix([[35, 44],
        [44, 56]])

In [27]:
C.sum()

21

In [28]:
C.sum(0)

matrix([[ 9, 12]])

In [29]:
C.sum(1)

matrix([[ 3],
        [ 7],
        [11]])

In [30]:
C.sum(2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [31]:
C.sum(axis=0)

matrix([[ 9, 12]])

In [33]:
cd ~/Dropbox/UTDallas/buan6340/post/

/home/jason/Dropbox/UTDallas/buan6340/post


In [34]:
bwght_df = pd.read_csv('BWGHT.csv')

In [35]:
bwght = bwght_df.values

In [36]:
bwght.shape

(1388, 14)

In [38]:
for pair in enumerate(bwght_df.columns): print(pair)

(0, 'faminc')
(1, 'cigtax')
(2, 'cigprice')
(3, 'bwght')
(4, 'fatheduc')
(5, 'motheduc')
(6, 'parity')
(7, 'male')
(8, 'white')
(9, 'cigs')
(10, 'lbwght')
(11, 'bwghtlbs')
(12, 'packs')
(13, 'lfaminc')


In [39]:
y = bwght[:,3]

In [41]:
(n,r) = bwght.shape

In [43]:
x = np.ones((n,1))

In [46]:
x = (x,bwght[:,7:10])
x = np.hstack(x)

In [ ]:
x = np.hstack((np.ones((n,1)),bwght[:,7:10]))

In [49]:
xx = np.dot(x.T,x)
xy = np.dot(x.T,y)
xxi = np.linalg.inv(xx)
np.dot(xxi,xy)

array([113.27770286,   3.05184325,   6.22970206,  -0.50572309])

In [50]:
xx = np.dot(x.T,x)
xy = np.dot(x.T,y)
np.linalg.solve(xx,xy)

array([113.27770286,   3.05184325,   6.22970206,  -0.50572309])

In [55]:
xx = np.dot(x.T,x)
xy = np.dot(x.T,y)
xxi = np.linalg.inv(xx)
b = np.linalg.solve(xx,xy)
e = y - np.dot(x,b)
vb = e.var()*xxi
se = np.sqrt(np.diagonal(vb))
tstat = np.divide(b,se)

In [62]:
from scipy.stats import norm
pval = 2*norm.cdf(-np.abs(tstat))

In [63]:
print(b)
print(se)
print(tstat)
print(pval)

[113.27770286   3.05184325   6.22970206  -0.50572309]
[1.30463496 1.06928496 1.29956484 0.08946234]
[86.827125    2.85409725  4.79368315 -5.65291601]
[0.00000000e+00 4.31593179e-03 1.63746828e-06 1.57748398e-08]
