In [3]:
import numpy as np
import pandas as pd
from lec4code import *
bwght_df = pd.read_csv('BWGHT.csv')
bwght = bwght_df.values
y = bwght[:,3]
x = bwght[:,7:10]
modela = lm(x,y)
modelb = white(x,y)

In [4]:
modela.tidy()

est   std.err     t.stat         p.val
0  113.277703  1.304635  86.827125  0.000000e+00
1    3.051843  1.069285   2.854097  4.315932e-03
2    6.229702  1.299565   4.793683  1.637468e-06
3   -0.505723  0.089462  -5.652916  1.577484e-08

In [5]:
modelb.tidy()

est   std.err     t.stat         p.val
0  113.277703  1.359358  83.331784  0.000000e+00
1    3.051843  1.068340   2.856621  4.281765e-03
2    6.229702  1.361156   4.576774  4.722022e-06
3   -0.505723  0.088601  -5.707862  1.144039e-08

In [43]:
n = 100
nsim = 1000
outp = np.zeros((nsim,1))
for isim in range(nsim):
    x = np.random.normal(size=(n,1))
    #e = np.random.normal(size=(n,1))
    e = np.random.normal(loc=0,scale=np.abs(x),size=(n,1))
    y = x + e
    #outp[isim,0] = lm(x,y).b[1]
    #model = lm(x,y)
    model = white(x,y)
    #outp[isim,0] = (model.b[1]-1)/model.se[1]
    tstat = (model.b[1]-1)/model.se[1]
    if abs(tstat)>1.96: outp[isim,0] = 1
print(outp.mean())
#print(outp.var())

0.079


In [46]:
nvec = [10,25,50,100,250]
svec = [0.5,1,2]
nsim = 1000
outp = np.zeros((nsim,len(nvec),len(svec)))
for j in range(len(svec)):
    sig = svec[j]
    for i in range(len(nvec)):
        n = nvec[i]
        for isim in range(nsim):
            x = np.random.normal(size=(n,1))
            e = np.random.normal(scale=sig,size=(n,1))
            y = x + e
            model = lm(x,y)
            outp[isim,i,j] = model.b[1]
#print(outp.mean(0))
print(outp.var(0))

[[0.03095481 0.1554387  0.58101399]
 [0.0123162  0.04461427 0.17129832]
 [0.00522067 0.01956924 0.09297911]
 [0.00241378 0.01070145 0.04132267]
 [0.00100574 0.00411904 0.01610655]]


In [47]:
from itertools import product
nvec = [10,25,50,100,250]
svec = [0.5,1,2]
nsim = 1000
outp = np.zeros((nsim,len(nvec),len(svec)))
pmat = [nvec,svec]
pmat = [range(len(a)) for a in pmat]
pmat = product(*pmat)
for i,j in pmat:
    (n,sig) = (nvec[i],svec[j])
    for isim in range(nsim):
        x = np.random.normal(size=(n,1))
        e = np.random.normal(scale=sig,size=(n,1))
        y = x + e
        model = lm(x,y)
        outp[isim,i,j] = model.b[1]
#print(outp.mean(0))
print(outp.var(0))

[[0.03683568 0.15269096 0.57419523]
 [0.01228649 0.04634985 0.18295671]
 [0.00506182 0.02220872 0.08092598]
 [0.00246743 0.01007115 0.04135977]
 [0.00105715 0.00387813 0.01538154]]


In [57]:
nvec = [10,25,50,100,250]
svec = [0.5,1,2]
pmat = [nvec,svec]
pmat = [range(len(a)) for a in pmat]
pmat = product(*pmat) #product(range(5),range(3))
for item in pmat:
    print(item)

(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)
(2, 0)
(2, 1)
(2, 2)
(3, 0)
(3, 1)
(3, 2)
(4, 0)
(4, 1)
(4, 2)


In [55]:
for a,b in product(range(1,10),range(1,10)):
    print(a,b)

1 1
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
2 1
2 2
2 3
2 4
2 5
2 6
2 7
2 8
2 9
3 1
3 2
3 3
3 4
3 5
3 6
3 7
3 8
3 9
4 1
4 2
4 3
4 4
4 5
4 6
4 7
4 8
4 9
5 1
5 2
5 3
5 4
5 5
5 6
5 7
5 8
5 9
6 1
6 2
6 3
6 4
6 5
6 6
6 7
6 8
6 9
7 1
7 2
7 3
7 4
7 5
7 6
7 7
7 8
7 9
8 1
8 2
8 3
8 4
8 5
8 6
8 7
8 8
8 9
9 1
9 2
9 3
9 4
9 5
9 6
9 7
9 8
9 9


In [61]:
np.arange(10)











a = [5,3]
a = [range(x) for x in a]
from itertools import product
for i in product(*a):
    print(i)

(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)
(2, 0)
(2, 1)
(2, 2)
(3, 0)
(3, 1)
(3, 2)
(4, 0)
(4, 1)
(4, 2)


In [74]:
n = 100000
nsim = 100
outp = np.zeros((nsim,1))
for isim in range(nsim):
    x = np.random.normal(size=(n,10))
    x = x.cumsum(0)
    e = np.random.normal(size=(n,1))
    e = e.cumsum().reshape(-1,1)
    y = e
    outp[isim,0] = lm(x,y).rsq
print(outp.mean())
print(outp.var())

0.7689508496973145
0.01889383617895003


In [63]:
np.arange(10).cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [76]:
a = 3
b = 2
x = 3
# Problem 1: Infinite loops
# Problem 2: Series that don't end in 1
lst = []
while x > 1:
    lst += [x]
    print(x)
    if x%2==0:
        x//=2
    else:
        x = a*x+b

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



KeyboardInterrupt: 

In [80]:
{20,10,5}=={10,5,20}

False